### ISSUE TITLE
[base-cluster] ImageCredentials get deleted upon reconciliation / upgrade

### ISSUE THREAD

**Issue by tmechsner** [teutonet/teutonet-helm-charts#461]
Hi, I just wanted to deploy a new image in one of our projects and didn't succeed.
I found that all pods were now receiving "permission denied" errors when trying to pull images.
After a short research I found that the secret created as specified in the section `global.imageCredentials` was missing.  Downgrading to base-chart version 4.5.1 solved the issue.

**Comment by cwrau** [comment]
Sorry for the late response 😕

The imagePullSecrets haven't changed since January, but I will take a look at it 👍️

**Comment by tmechsner** [comment]
We downgraded to version 4.5.1 again because after the update the ImagePullSecrets stopped working (the image containing the secrets was gone). We update again in a few days and will let you know if it worked.

**Comment by tmechsner** [comment]
@cwrau I just updated to 4.5.3 and our "docker-hub" secret is gone again.

**Comment by cwrau** [comment]
> @cwrau I just updated to 4.5.3 and our "docker-hub" secret is gone again.

I just reconciled the HelmRelease and the secret appeared again. But it's weird, on every reconcile the secret gets recreated 🤔

**Comment by tmechsner** [comment]
Strange. Isn't the reconcilation process involved in updates anyways?

**Comment by cwrau** [comment]
I debugged your stuff for a while and my suspicions seems true, the delete policy has a default which leads to the secret being deleted

I have *no idea* why it didn't get recreated for you after that tho 😅

So we're going to remove the hook settings, I don't think that's going to cause much trouble, at least less than what's happening now 😅

The customer is recommended to use `4.x.x` as the version in the HelmRelease so that updates get rolled out automatically and therefore stuff like this shouldn't result in a recreate, even if it would've worked
